#!/usr/bin/env python3
"""Generate the frozen DRY-D1 positive-control tolerance bank [AUTH: 00 §34B.1A; 02 §C5].

02 §C5 binds a positive-control cutoff to the implementation it was generated from and
forbids preserving an old numerical tolerance merely because it passed. The DRY-D statistic's
authoritative retained-rank schedule was corrected from ten interior ranks to the twelve of
00 §28B.1, so the DRY-D1 cutoffs are regenerated here, once, before any real outcome exists.

This runs the SAME canonical statistic validation runs — `generate_tail_trial` over
`DRY_D_INTERIOR_RANKS` with the frozen planted-effect design — differing only in the master
seed. There is no separate, easier calibration path.

Output is the canonical 00 §34B.2 artifact:

    artifacts/p0_pre/P0_PRE_00_DRYRUN_TOLERANCE_CALIBRATION.json

carrying the complete 200-value bank for each arm, not only the two cutoffs: the bank is the
scientific provenance, and a cutoff nobody can re-derive is not calibrated evidence.

CLI
    python scripts/calibrate_dryrun_tolerances.py --root . [--verify]
Exit
    0 = generated, or verified consistent; 1 = the artifact and a fresh run disagree
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.analysis.dryrun import (  # noqa: E402
    CALIBRATION_QUANTILE_METHOD,
    DRY_D_ANCHOR_RANKS,
    DRY_D_FIXTURE_ITERATIONS,
    DRY_D_INTERIOR_RANKS,
    DRY_D_TRIAL_STATISTIC,
    SUPERSEDED_DRY_D1_MINK_MAX,
    SUPERSEDED_DRY_D1_REFERENCE_MAX,
    SUPERSEDED_THRESHOLD_STATUS,
    calibrate_dry_d1_positive_control,
)
from src.analysis.settings import dry_run_settings  # noqa: E402

ARTIFACT_REL = "artifacts/p0_pre/P0_PRE_00_DRYRUN_TOLERANCE_CALIBRATION.json"
SCHEMA = "p0-pre.dryrun-tolerance-calibration.v1"

#: 02 §C5: freeze pass thresholds giving at least 95% synthetic detection probability.
REQUIRED_POWER = 0.95

#: The generator's fixture geometry, recorded so the bank can be interpreted without reading
#: the source. These describe `_tail_geometry`; they are not a second copy that can drift,
#: because the regeneration check below re-runs the real generator.
FIXTURE = {
    "surface": {"w0": [40, 36], "w1": [40, 36]},
    "protected_structural_rank": 32,
    "partner_structural_rank": 8,
    "k_descendants": 4,
    "alpha": 0.5,
    "operator": "O3_SVD_TRUNC_MERGE",
    "c2_sweeps": DRY_D_FIXTURE_ITERATIONS,
    "recovery_profile": "FIXTURE_ONLY_NOT_SCIENTIFIC",
}


def code_identity(root: Path) -> str:
    """A content hash over the modules the bank was generated by [AUTH: 02 §C7 in spirit]."""
    digest = hashlib.sha256(SCHEMA.encode())
    for relative in (
        "src/analysis/dryrun.py",
        "src/recovery/solvers.py",
        "src/recovery/observations.py",
        "src/recovery/context.py",
        "src/recovery/evaluation.py",
        "src/merge/operators.py",
        "src/merge/family.py",
    ):
        digest.update(relative.encode())
        digest.update((root / relative).read_bytes())
    return digest.hexdigest()


def build(root: Path) -> dict[str, Any]:
    settings = dry_run_settings(root)
    start = settings.integer("dry_d1_calibration_seed_start")
    trials = settings.integer("dry_d1_calibration_trials")
    quantile = settings.number("dry_d1_quantile")
    shift = settings.number("dry_d1_planted_shift")
    seeds = list(range(start, start + trials))

    bank = calibrate_dry_d1_positive_control(seeds, planted_shift=shift, quantile=quantile)
    reference, mink = bank["reference"], bank["mink"]

    return {
        "schema": SCHEMA,
        "status": "FROZEN",
        "authority": "00 §34B.1A, §34B.2; 02 §C5",
        "generated_pre_real_data": True,
        "scenario": "DRY_D1",
        "statistic": DRY_D_TRIAL_STATISTIC,
        "statistic_code_sha256": code_identity(root),
        "dry_run_config_sha256": settings.sha256,
        "master_seeds": seeds,
        "n_trials": trials,
        "rank_schedule": {
            "anchors": list(DRY_D_ANCHOR_RANKS),
            "interior": list(DRY_D_INTERIOR_RANKS),
            "interior_count": len(DRY_D_INTERIOR_RANKS),
        },
        "fixture": FIXTURE,
        "planted_effect": {
            "reference_shift": shift,
            "mink_shift": shift,
            "noise": "normal(rng(master_seed + 1), 2)[0] * 0.01; Min-K% scaled by 0.5",
            "sign": "NEGATIVE",
            "detection_rule": "statistic < threshold",
        },
        "quantile": quantile,
        "quantile_method": CALIBRATION_QUANTILE_METHOD,
        "reference_statistics": list(reference.values),
        "mink_statistics": list(mink.values),
        "threshold_reference": reference.threshold,
        "threshold_mink": mink.threshold,
        "empirical_power_reference": reference.empirical_power,
        "empirical_power_mink": mink.empirical_power,
        "required_power": REQUIRED_POWER,
        "superseded": {
            "threshold_reference": SUPERSEDED_DRY_D1_REFERENCE_MAX,
            "threshold_mink": SUPERSEDED_DRY_D1_MINK_MAX,
            "status": SUPERSEDED_THRESHOLD_STATUS,
            "reason": (
                "generated against a ten-interior-rank DRY-D implementation; the authoritative"
                " 00 §28B.1 schedule has twelve interior ranks, so 02 §C5 requires regeneration"
                " rather than preservation"
            ),
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".")
    parser.add_argument("--verify", action="store_true")
    arguments = parser.parse_args()
    root = Path(arguments.root).resolve()
    path = root / ARTIFACT_REL

    document = build(root)
    for arm in ("reference", "mink"):
        power = float(document[f"empirical_power_{arm}"])
        if power < REQUIRED_POWER:
            print(
                f"calibrate_dryrun_tolerances: {arm} arm power {power:.4f} < {REQUIRED_POWER}"
                " [AUTH: 02 §C5] — reporting rather than strengthening the planted effect",
                file=sys.stderr,
            )
            return 1

    rendered = json.dumps(document, indent=2, sort_keys=True) + "\n"
    if arguments.verify:
        if not path.exists():
            print(f"calibrate_dryrun_tolerances: {ARTIFACT_REL} is missing", file=sys.stderr)
            return 1
        if path.read_text(encoding="utf-8") != rendered:
            print(
                f"calibrate_dryrun_tolerances: {ARTIFACT_REL} does not match a fresh run",
                file=sys.stderr,
            )
            return 1
        print(f"calibrate_dryrun_tolerances: {ARTIFACT_REL} verified")
        return 0

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rendered, encoding="utf-8")
    print(
        f"calibrate_dryrun_tolerances: wrote {ARTIFACT_REL}\n"
        f"  threshold_reference = {document['threshold_reference']!r}"
        f"  power = {document['empirical_power_reference']:.4f}\n"
        f"  threshold_mink      = {document['threshold_mink']!r}"
        f"  power = {document['empirical_power_mink']:.4f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
