"""S02 deterministic offline fixtures [AUTH: 01 §20, §8B; 00 §8.3, §10.1, §25 P0-C1].

No network, no GPU, no research model. The identities asserted here (ΔW = BA, the linear
merge, the C1 oracle inversion) are exact algebra, so they are asserted as algebra rather
than as tolerances wherever float64 permits it.
"""

from __future__ import annotations

import socket
from pathlib import Path
from typing import Any

import numpy as np
import pytest

from src.models.fixtures import (
    FIXTURE_SCHEMA,
    LORA_TARGET_MODULES,
    FixtureError,
    FixtureSpec,
    adapter_updates,
    build_base_model,
    build_canary_records,
    build_corpus,
    build_tokenizer,
    induced_update,
    linear_merge,
    load_fixture_spec,
    load_state_dict,
    lora_factors,
    matrix_rank,
    model_config_document,
    numeric_fingerprint,
    oracle_invert_linear,
    parameter_count,
    save_state_dict,
    state_fingerprints,
    stream_values,
    target_parameter_names,
)
from src.provenance.config import resolve_config
from src.provenance.hashing import read_canonical_json, sha256_canonical

#: Merge coefficients are material and therefore never a source default in src/; the test
#: declares its own so the fixture algebra is exercised with explicit values [AUTH: 01 §17].
TEST_MERGE_COEFFICIENTS: dict[str, float] = {"hidden": 0.6, "partner": 0.4}
GOLDEN_REL = "tests/fixtures/s02_fixture_golden.json"


@pytest.fixture(scope="module")
def spec(repo_root: Path) -> FixtureSpec:
    resolved = resolve_config(
        repo_root / "configs" / "models" / "tiny_fixture.json",
        config_root=repo_root / "configs",
        schema=FIXTURE_SCHEMA,
    )
    return load_fixture_spec(resolved)


def golden_document(spec: FixtureSpec) -> dict[str, Any]:
    """The frozen numeric contract. Regenerated by the test and by the generator alike."""
    base = build_base_model(spec)
    hidden = adapter_updates(spec, base, "hidden")
    partner = adapter_updates(spec, base, "partner")
    merged = linear_merge(base, {"hidden": hidden, "partner": partner}, TEST_MERGE_COEFFICIENTS)
    return {
        "schema": "s02.fixture-golden.v1",
        "merge_coefficients": TEST_MERGE_COEFFICIENTS,
        "parameter_count": parameter_count(base),
        "base_model": state_fingerprints(base),
        "adapter_updates": {
            "hidden": state_fingerprints(hidden),
            "partner": state_fingerprints(partner),
        },
        "merged": state_fingerprints(merged),
        "corpus_sha256": sha256_canonical(build_corpus(spec)),
        "canary_sha256": sha256_canonical(build_canary_records(spec)),
        "tokenizer_sha256": sha256_canonical(build_tokenizer(spec)),
        "model_config_sha256": sha256_canonical(model_config_document(spec)),
    }


# ------------------------------------------------------------------ contract 21
def test_generation_is_deterministic(spec: FixtureSpec) -> None:
    assert state_fingerprints(build_base_model(spec)) == state_fingerprints(build_base_model(spec))
    assert build_corpus(spec) == build_corpus(spec)
    assert np.array_equal(stream_values("label", 8), stream_values("label", 8))
    assert not np.array_equal(stream_values("label", 8), stream_values("other", 8))


def test_generation_matches_the_frozen_golden_contract(repo_root: Path, spec: FixtureSpec) -> None:
    """A change in any fixture number must be a deliberate golden update, never a surprise."""
    frozen = read_canonical_json(repo_root / GOLDEN_REL)
    assert golden_document(spec) == frozen


# ------------------------------------------------------------------ contract 22
def test_no_network_is_required(spec: FixtureSpec, monkeypatch: pytest.MonkeyPatch) -> None:
    def refuse(*args: object, **kwargs: object) -> None:
        raise AssertionError("a fixture attempted network access [AUTH: 01 §20]")

    monkeypatch.setattr(socket, "socket", refuse)
    monkeypatch.setattr(socket, "create_connection", refuse)
    base = build_base_model(spec)
    adapter_updates(spec, base, "hidden")
    build_corpus(spec)
    build_canary_records(spec)
    build_tokenizer(spec)


# ------------------------------------------------------------------ contract 23
def test_the_induced_update_is_exactly_scaled_ba(spec: FixtureSpec) -> None:
    base = build_base_model(spec)
    name = target_parameter_names(spec)[0]
    rows, columns = base[name].shape
    a, b = lora_factors(spec, "hidden", name, (rows, columns))
    assert a.shape == (spec.lora_rank, columns)
    assert b.shape == (rows, spec.lora_rank)
    delta = induced_update(a, b, spec.lora_scaling)
    assert np.array_equal(delta, spec.lora_scaling * (b @ a))
    assert delta.shape == (rows, columns)


def test_rank_32_is_structurally_real(spec: FixtureSpec) -> None:
    """Rank is a property of ΔW, not a label: every targeted update has exactly rank 32."""
    assert spec.lora_rank == 32
    base = build_base_model(spec)
    updates = adapter_updates(spec, base, "hidden")
    assert set(updates) == set(target_parameter_names(spec))
    for name, delta in updates.items():
        assert min(delta.shape) > spec.lora_rank, name
        assert matrix_rank(delta) == spec.lora_rank, name


def test_only_the_8b_mlp_matrices_are_targeted(spec: FixtureSpec) -> None:
    targets = target_parameter_names(spec)
    assert len(targets) == spec.num_hidden_layers * len(LORA_TARGET_MODULES)
    assert all(".mlp." in name for name in targets)
    assert not any(
        "embed_tokens" in name or "lm_head" in name or "self_attn" in name for name in targets
    )


def test_mismatched_lora_factors_fail_closed() -> None:
    with pytest.raises(FixtureError, match="inner dimensions"):
        induced_update(np.zeros((4, 8)), np.zeros((8, 5)), 1.0)


# ------------------------------------------------------------------ contract 24
def test_linear_merge_matches_analytic_ground_truth(spec: FixtureSpec) -> None:
    base = build_base_model(spec)
    hidden = adapter_updates(spec, base, "hidden")
    partner = adapter_updates(spec, base, "partner")
    merged = linear_merge(base, {"hidden": hidden, "partner": partner}, TEST_MERGE_COEFFICIENTS)
    for name, array in base.items():
        expected = array.copy()
        if name in hidden:
            expected = (
                expected
                + TEST_MERGE_COEFFICIENTS["hidden"] * hidden[name]
                + TEST_MERGE_COEFFICIENTS["partner"] * partner[name]
            )
        assert np.allclose(merged[name], expected, rtol=0.0, atol=0.0), name
    untouched = [n for n in base if n not in hidden]
    assert untouched, "the merge must leave non-target parameters alone"
    for name in untouched:
        assert np.array_equal(merged[name], base[name])


def test_a_merge_without_a_coefficient_fails_closed(spec: FixtureSpec) -> None:
    base = build_base_model(spec)
    with pytest.raises(FixtureError, match="no merge coefficient"):
        linear_merge(base, {"hidden": adapter_updates(spec, base, "hidden")}, {})


# ------------------------------------------------------------------ contract 25
def test_oracle_inversion_recovers_the_hidden_constituent(spec: FixtureSpec) -> None:
    base = build_base_model(spec)
    hidden = adapter_updates(spec, base, "hidden")
    partner = adapter_updates(spec, base, "partner")
    merged = linear_merge(base, {"hidden": hidden, "partner": partner}, TEST_MERGE_COEFFICIENTS)
    recovered = oracle_invert_linear(
        merged, base, {"partner": partner}, TEST_MERGE_COEFFICIENTS, "hidden"
    )
    assert set(recovered) == set(hidden)
    for name, truth in hidden.items():
        assert np.allclose(recovered[name], truth, rtol=1e-12, atol=1e-12), name
        assert matrix_rank(recovered[name]) == spec.lora_rank


def test_inversion_may_not_be_handed_the_hidden_adapter(spec: FixtureSpec) -> None:
    base = build_base_model(spec)
    hidden = adapter_updates(spec, base, "hidden")
    merged = linear_merge(base, {"hidden": hidden}, {"hidden": 1.0})
    with pytest.raises(FixtureError, match="may not be supplied"):
        oracle_invert_linear(merged, base, {"hidden": hidden}, {"hidden": 1.0}, "hidden")
    with pytest.raises(FixtureError, match="no non-zero coefficient"):
        oracle_invert_linear(merged, base, {}, {"hidden": 0.0}, "hidden")


# ------------------------------------------------------------------ contract 26
def test_save_load_preserves_the_scientific_values(tmp_path: Path, spec: FixtureSpec) -> None:
    base = build_base_model(spec)
    path = tmp_path / "model.safetensors"
    save_state_dict(path, base)
    reloaded = load_state_dict(path)
    assert set(reloaded) == set(base)
    for name, array in base.items():
        assert reloaded[name].shape == array.shape, name
        # float32 on disk, as a real checkpoint would be; the identity survives the round trip.
        assert np.allclose(reloaded[name], array, rtol=1e-6, atol=1e-7), name


def test_a_reloaded_fixture_still_supports_the_algebra(tmp_path: Path, spec: FixtureSpec) -> None:
    base = build_base_model(spec)
    path = tmp_path / "model.safetensors"
    save_state_dict(path, base)
    reloaded = load_state_dict(path)
    hidden = adapter_updates(spec, reloaded, "hidden")
    merged = linear_merge(reloaded, {"hidden": hidden}, {"hidden": 1.0})
    recovered = oracle_invert_linear(merged, reloaded, {}, {"hidden": 1.0}, "hidden")
    for name, truth in hidden.items():
        assert np.allclose(recovered[name], truth, rtol=1e-10, atol=1e-10), name


# ------------------------------------------------------------------ contract 27
def test_fixture_corruption_is_detected(tmp_path: Path, spec: FixtureSpec) -> None:
    base = build_base_model(spec)
    name = target_parameter_names(spec)[0]
    before = numeric_fingerprint(base[name])

    corrupted = {k: v.copy() for k, v in base.items()}
    corrupted[name][0, 0] += 1e-9
    assert numeric_fingerprint(corrupted[name]) != before
    assert state_fingerprints(corrupted) != state_fingerprints(base)

    path = tmp_path / "model.safetensors"
    save_state_dict(path, base)
    from src.provenance.hashing import ArtifactVerificationError, record_artifact, verify_artifact

    record = record_artifact(tmp_path, "model.safetensors")
    save_state_dict(path, corrupted)
    with pytest.raises(ArtifactVerificationError):
        verify_artifact(tmp_path, record)


def test_a_reshaped_array_is_not_the_same_fingerprint() -> None:
    flat = np.arange(6, dtype=np.float64)
    assert numeric_fingerprint(flat.reshape(2, 3)) != numeric_fingerprint(flat.reshape(3, 2))


# ------------------------------------------------------------------ config-driven, fail-closed
def test_the_spec_comes_from_config_not_from_source(spec: FixtureSpec) -> None:
    assert spec.lora_rank == 32
    assert spec.lora_scaling == spec.lora_alpha / spec.lora_rank
    assert spec.role == "TEST_FIXTURE_NOT_A_RESEARCH_SUBJECT"
    assert model_config_document(spec)["hidden_size"] == spec.hidden_size


def test_a_rank_larger_than_the_target_fails_closed(repo_root: Path) -> None:
    resolved = dict(
        resolve_config(
            repo_root / "configs" / "models" / "tiny_fixture.json",
            config_root=repo_root / "configs",
            schema=FIXTURE_SCHEMA,
        )
    )
    resolved["lora_rank"] = 4096
    with pytest.raises(FixtureError, match="could not have that rank"):
        load_fixture_spec(resolved)


def test_a_non_8b_target_policy_fails_closed(repo_root: Path) -> None:
    resolved = dict(
        resolve_config(
            repo_root / "configs" / "models" / "tiny_fixture.json",
            config_root=repo_root / "configs",
            schema=FIXTURE_SCHEMA,
        )
    )
    resolved["lora_target_modules"] = ["q_proj"]
    with pytest.raises(FixtureError, match="MLP policy"):
        load_fixture_spec(resolved)


def test_bad_dimensions_fail_closed(repo_root: Path) -> None:
    base = dict(
        resolve_config(
            repo_root / "configs" / "models" / "tiny_fixture.json",
            config_root=repo_root / "configs",
            schema=FIXTURE_SCHEMA,
        )
    )
    for key, value, match in (
        ("hidden_size", 65, "divisible"),
        ("vocab_size", 0, "positive integer"),
        ("num_hidden_layers", "two", "positive integer"),
    ):
        resolved = dict(base)
        resolved[key] = value
        with pytest.raises(FixtureError, match=match):
            load_fixture_spec(resolved)


def test_records_are_disjoint_and_labelled(spec: FixtureSpec) -> None:
    corpus = build_corpus(spec)
    canaries = build_canary_records(spec)
    assert len(corpus) == spec.corpus_records
    assert len(canaries) == spec.canary_records
    assert not {r["record_id"] for r in corpus} & {r["record_id"] for r in canaries}
    assert all(r["is_canary"] is False for r in corpus)
    assert all(r["is_canary"] is True for r in canaries)
